### PR TITLE
add # comment; compile with float; add tests; add Bob.txt

### PR DESCRIPTION
**Pull request by maarten-boot**
to compile with Float bobini.c needed a extra declaration.
added # as single line comment
added test dir and a set of simple tests all can be executed from the test directory with all_tests.sh. 
  all tests run successfully to the end 
converted Bob.doc to Bob.txt and removed the line: "break expression ;" in the syntax of break-statement as it does not match the code.

### CODE REVIEW

**Comment by dbetz** [comment]
I manually merged in your single line comment change. I'm not sure what's going on with the declaration in bobint.c. The branch seems to build fine with out it. Where is "m" referenced?

**Comment by dbetz** [comment]
Sorry. It looks like GitHub won't allow me to merge just the test part of your changes now that I manually inserted the # comment code. Can you submit another pull request with just the tests?

**Comment by maarten-boot** [comment]
m was my error , compiled the code before cleaning all the matrix stuff in
bobint.c
retracted the pull requesta dn made a new one just with the tests

you may want to remove the break expression; from the syntax as it seems
not supported by the actual code
see the Bob.doc file  page 5

break-statement:
    break ;
    break expression ;

**Comment by maarten-boot** [comment]
question about some details:

method.Apply() seems to need minimal 3 arguments but the second seems never
actually used so i cannot figure out why it is there,
// see test/test_library.bob

Symbol.printName: i could find no actual use for it
what i could come up with is:
    a = 5;
    stdout.Display(\a, " ", \a.printName,"\n");
they give the same output namely: a
so in what context would printName actually be helpful?
// see test/test_vector.bob

**Comment by maarten-boot** [comment]
another detail

in bobcom.c do_function you test for T_STRING in switch but not at the end
if (tkn == T_IDENTIFIER) {
i thin k that should have been
if ( ( tkn == T_IDENTIFIER ) | ( tkn == T_STRING ) ) {

/* do_function - parse a regular definition */
static void do_function(BobCompiler *c,PVAL *pv)
{
    char name[256];
    int nameP,tkn;

    /* check for a function name */
    switch (tkn = BobToken(c)) {
    case T_IDENTIFIER:
    case T_STRING:
        strcpy(name,c->t_token);
        nameP = TRUE;
        break;
    default:
        BobSaveToken(c,tkn);
        nameP = FALSE;
        break;
    }

    /* compile function body */
    compile_code(c,nameP ? name : NULL);

    /* store the function as the value of the global symbol */
    if (tkn == T_IDENTIFIER) {
        putcbyte(c,BobOpGSET);
        putcword(c,make_lit_symbol(c,name));
    }
    pv->fcn = NULL;
}

**Comment by dbetz** [comment]
I can't recall why I allowed strings. Does Javascript allow them? This might have been part of my attempt to align better with Javascript. I guess the T_STRING cases can be removed.

**Comment by dbetz** [comment]
> m was my error , compiled the code before cleaning all the matrix stuff in bobint.c retracted the pull requesta dn made a new one just with the tests you may want to remove the break expression; from the syntax as it seems not supported by the actual code see the Bob.doc file page 5 break-statement: break ; break expression ;
> […](#)

I'm thinking this should probably be considered a bug. It seems like "break <expr>" would be a useful feature.

**Comment by dbetz** [comment]
I merged your test directory but should there be an addition to the Makefile to run the tests? Also, I need to fix the dependencies in the Makefile since nothing gets rebuilt automatically if you change one of the source files. I always have to do "make clean" before "make" to get things to rebuild. That's my bug of course!

**Comment by maarten-boot** [comment]
Will look into adding a make test.
Yes i noted the 3 makefiles are complicating things possibly use the single
one you have in the older bob.

**Comment by dbetz** [comment]
I merged all of the Makefiles together as you suggested.

**Comment by dbetz** [comment]
I removed the version of break that takes an argument from the doc file and I added a PDF export of the doc.

**Comment by dbetz** [comment]
I think I now recall why T_STRING is allowed after the "function" keyword. The idea is to provide a string to be used as a name when the function object is printed. If you supply a T_IDENTIFIER then the symbol with that name gets set to the function object. The T_STRING just gets used for printing. That's why they are handled differently.

**Comment by maarten-boot** [comment]
Makes sense

**Pull request closed without merging**
